services:
  - type: web
    name: processgat-xl
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
